import { type ChordType } from '@workspace/studio-core';

export interface CategoryItem {
  type: ChordType;
  icon: string;
  label: string;
  desc: string;
  wide?: boolean;
  noDecor?: boolean;
  color: string;
  variations: string;
  dots: { stringPercent: number; fretPercent: number }[];
  sampleChordId?: string;
}

export const CATEGORIES: CategoryItem[] = [
  {
    type: 'major',
    icon: 'piano',
    label: 'Major',
    desc: 'Bright, happy, foundational.',
    wide: true,
    noDecor: true,
    color: '#679cff',
    variations: '84 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 33 },
    ],
    sampleChordId: 'C-major',
  },
  {
    type: 'minor',
    icon: 'dark_mode',
    label: 'Minor',
    desc: 'Moody & emotional.',
    color: '#bb5551',
    variations: '72 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-minor',
  },
  {
    type: '7th',
    icon: 'electric_bolt',
    label: '7th',
    desc: 'Jazz & blues backbone.',
    color: '#9d9da6',
    variations: '64 Variations',
    dots: [{ stringPercent: 50, fretPercent: 33 }],
    sampleChordId: 'C-7th',
  },
  {
    type: 'maj7',
    icon: 'stars',
    label: 'Maj7',
    desc: 'Lush & dreamy.',
    color: '#679cff',
    variations: '56 Variations',
    dots: [{ stringPercent: 84, fretPercent: 66 }],
    sampleChordId: 'C-maj7',
  },
  {
    type: 'min7',
    icon: 'nightlight',
    label: 'Min7',
    desc: 'Smooth & introspective.',
    color: '#bb5551',
    variations: '56 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-min7',
  },
  {
    type: 'dim',
    icon: 'warning',
    label: 'Dim',
    desc: 'Tense & dissonant.',
    color: '#ee7d77',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 33 },
    ],
    sampleChordId: 'C-dim',
  },
  {
    type: 'aug',
    icon: 'trending_up',
    label: 'Aug',
    desc: 'Mysterious & floating.',
    color: '#9d9da6',
    variations: '18 Variations',
    dots: [{ stringPercent: 84, fretPercent: 33 }],
    sampleChordId: 'C-aug',
  },
  {
    type: 'sus2',
    icon: 'waves',
    label: 'Sus2',
    desc: 'Open & airy.',
    color: '#2dd4bf',
    variations: '42 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-sus2',
  },
  {
    type: 'sus4',
    icon: 'hourglass_empty',
    label: 'Sus4',
    desc: 'Suspended tension.',
    color: '#2dd4bf',
    variations: '42 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-sus4',
  },
  {
    type: '9th',
    icon: 'tune',
    label: '9th',
    desc: 'Rich & funky.',
    color: '#b57bee',
    variations: '48 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-9th',
  },
  {
    type: 'maj9',
    icon: 'auto_awesome',
    label: 'Maj9',
    desc: 'Romantic & complex.',
    color: '#b57bee',
    variations: '36 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-maj9',
  },
  {
    type: 'min9',
    icon: 'cloud',
    label: 'Min9',
    desc: 'Dark & jazzy.',
    color: '#b57bee',
    variations: '36 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-min9',
  },
  {
    type: 'add9',
    icon: 'add_circle',
    label: 'Add9',
    desc: 'Major with color.',
    color: '#34d399',
    variations: '30 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-add9',
  },
  {
    type: '6th',
    icon: 'hexagon',
    label: '6th',
    desc: 'Sweet & vintage.',
    color: '#fbbf24',
    variations: '32 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-6th',
  },
  {
    type: 'min6',
    icon: 'star_half',
    label: 'Min6',
    desc: 'Bittersweet.',
    color: '#fbbf24',
    variations: '32 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 33 },
    ],
    sampleChordId: 'C-min6',
  },
  {
    type: 'halfdim',
    icon: 'contrast',
    label: 'Half-Dim ø7',
    desc: 'Jazz & classical tension.',
    color: '#ee7d77',
    variations: '28 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-halfdim',
  },
  {
    type: 'dim7',
    icon: 'block',
    label: 'Dim7',
    desc: 'Symmetrical & eerie.',
    color: '#ee7d77',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-dim7',
  },
  {
    type: '11th',
    icon: 'stacked_bar_chart',
    label: '11th',
    desc: 'Dense & modern.',
    color: '#b57bee',
    variations: '24 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-11th',
  },
  {
    type: 'min11',
    icon: 'stacked_bar_chart',
    label: 'Min11',
    desc: 'Mellow minor 11th.',
    color: '#b57bee',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-min11',
  },
  {
    type: '13th',
    icon: 'equalizer',
    label: '13th',
    desc: 'Full jazz voicing.',
    color: '#b57bee',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-13th',
  },
  {
    type: 'min13',
    icon: 'equalizer',
    label: 'Min13',
    desc: 'Rich minor 13th.',
    color: '#b57bee',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-min13',
  },
  {
    type: '7sus4',
    icon: 'pending',
    label: '7sus4',
    desc: 'Funky & unresolved.',
    color: '#34d399',
    variations: '20 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-7sus4',
  },
  {
    type: '7sus2',
    icon: 'radio_button_unchecked',
    label: '7sus2',
    desc: 'Open dominant.',
    color: '#34d399',
    variations: '20 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-7sus2',
  },
  {
    type: 'maj6',
    icon: 'grade',
    label: 'Maj6',
    desc: 'Vintage & melodic.',
    color: '#fbbf24',
    variations: '24 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-maj6',
  },
  {
    type: 'power',
    icon: 'flash_on',
    label: 'Power',
    desc: 'Rock & metal essential.',
    color: '#ee7d77',
    variations: '16 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 66 },
    ],
    sampleChordId: 'C-power',
  },
  {
    type: 'minmaj7',
    icon: 'merge',
    label: 'm/maj7',
    desc: 'Jazz sophistication.',
    color: '#b57bee',
    variations: '18 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-minmaj7',
  },
  {
    type: 'aug7',
    icon: 'north_east',
    label: 'Aug7',
    desc: 'Tense jazz transition.',
    color: '#2dd4bf',
    variations: '16 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-aug7',
  },
  {
    type: '7b9',
    icon: 'south',
    label: '7b9',
    desc: 'Dark Spanish-jazz tension.',
    color: '#ee7d77',
    variations: '18 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 50, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-7b9',
  },
  {
    type: '7s9',
    icon: 'bolt',
    label: '7#9',
    desc: 'The Hendrix chord.',
    color: '#9d9da6',
    variations: '18 Variations',
    dots: [
      { stringPercent: 50, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 33 },
    ],
    sampleChordId: 'C-7s9',
  },
  {
    type: '69',
    icon: 'grain',
    label: '6/9',
    desc: 'Jazz & bossa nova color.',
    color: '#fbbf24',
    variations: '20 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 66 },
      { stringPercent: 50, fretPercent: 66 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-69',
  },
  {
    type: '9sus4',
    icon: 'blur_on',
    label: '9sus4',
    desc: 'Soulful & unresolved.',
    color: '#34d399',
    variations: '16 Variations',
    dots: [
      { stringPercent: 16, fretPercent: 33 },
      { stringPercent: 84, fretPercent: 66 },
    ],
    sampleChordId: 'C-9sus4',
  },
];
