// Export everything from studio-core
export * from './store/useChordStore';
export * from './store/useDrumStore';
export * from './hooks/useIsWebDesktop';
export * from './hooks/useStudioPreferences';
export * from './hooks/useStudioShortcuts';
export * from './data/chords';
export * from './data/progressions';
export * from './data/songs';
export * from './data/progressionsEs';
export * from './lib/accountStatus';
export * from './lib/activityLogger';
export * from './lib/adminConfig';
export * from './lib/apkDownloader';
export * from './lib/appVersion';
export * from './lib/assetCache';
export * from './lib/audioContextOptions';
export * from './lib/auth';
export * from './lib/backStack';
export * from './lib/capgoUpdater';
export * from './lib/chordAssistant';
export * from './lib/chordDetect';
export * from './lib/drumAudio';
export * from './lib/drumLibrary';
export * from './lib/drumPlugins';
export * from './lib/firebase';
export * from './lib/guitarAudio';
export * from './lib/i18n';
export * from './lib/i18nSetup';
export * from './lib/liquidGlass';
export * from './lib/nativePrefs';
export * from './lib/navScroll';
export * from './lib/otaUpdate';
export * from './lib/permissions';
export * from './lib/progressionGen';
export * from './lib/pushNotifications';
export * from './lib/security';
export * from './lib/studioAppNavigationRegistry';
export * from './lib/studioShortcutRegistry';
export * from './lib/supabaseClient';
export * from './lib/sync';
export * from './lib/transpose';
export * from './lib/useLiquidGlassNav';
export * from './lib/userAvatar';
export * from './lib/useStatusBar';
export * from './lib/useT';
export * from './lib/utils';
export * from './lib/syncBackends/index';
export * from './vocalex/labSessionDb';
export * from './vocalex/takesDb';
export { applyUpdate } from './lib/capgoUpdater';
export { type Language, default as translations } from './lib/i18n';
export * from './lib/devTools';
export * from './lib/lyricsService';


